$(function () {
    // 顶部切换
    $('.nav1').on('click', function () {
        $('.banner').show()
        $('.bg').hide()
        $('.home').show()
        $('.schoolProfile').hide()
        $('.schoolDynamics').hide()
        $('.specialtyDepartment').hide()
        $('.specialist').hide()
        $('.campusOverview').hide()
        $('.schoolEnterpriseCooperation').hide()
        $('.contactUs').hide()
    })
    $('.navTitle1').on('click', function () {
        $('.banner').hide()
        $('.bg').show()
        $('.home').hide()
        $('.schoolProfile').show()
        $('.schoolDynamics').hide()
        $('.specialtyDepartment').hide()
        $('.specialist').hide()
        $('.campusOverview').hide()
        $('.schoolEnterpriseCooperation').hide()
        $('.contactUs').hide()
    })
    $('.navTitle2').on('click', function () {
        $('.banner').hide()
        $('.bg').hide()
        $('.home').hide()
        $('.schoolProfile').hide()
        $('.schoolDynamics').show()
        $('.specialtyDepartment').hide()
        $('.specialist').hide()
        $('.campusOverview').hide()
        $('.schoolEnterpriseCooperation').hide()
        $('.contactUs').hide()
    })
    $('.navTitle3').on('click', function () {
        $('.banner').hide()
        $('.bg').hide()
        $('.home').hide()
        $('.schoolProfile').hide()
        $('.schoolDynamics').hide()
        $('.specialtyDepartment').show()
        $('.specialist').hide()
        $('.campusOverview').hide()
        $('.schoolEnterpriseCooperation').hide()
        $('.contactUs').hide()
    })
    $('.navTitle4').on('click', function () {
        $('.banner').hide()
        $('.bg').hide()
        $('.home').hide()
        $('.schoolProfile').hide()
        $('.schoolDynamics').hide()
        $('.specialtyDepartment').hide()
        $('.specialist').show()
        $('.campusOverview').hide()
        $('.schoolEnterpriseCooperation').hide()
        $('.contactUs').hide()
    })
    $('.navTitle5').on('click', function () {
        $('.banner').hide()
        $('.bg').hide()
        $('.home').hide()
        $('.schoolProfile').hide()
        $('.schoolDynamics').hide()
        $('.specialtyDepartment').hide()
        $('.specialist').hide()
        $('.campusOverview').show()
        $('.schoolEnterpriseCooperation').hide()
        $('.contactUs').hide()
    })
    $('.navTitle6').on('click', function () {
        $('.banner').hide()
        $('.bg').hide()
        $('.home').hide()
        $('.schoolProfile').hide()
        $('.schoolDynamics').hide()
        $('.specialtyDepartment').hide()
        $('.specialist').hide()
        $('.campusOverview').hide()
        $('.schoolEnterpriseCooperation').show()
        $('.contactUs').hide()
    })
    $('.nav8').on('click', function () {
        $('.banner').hide()
        $('.bg').hide()
        $('.home').hide()
        $('.schoolProfile').hide()
        $('.schoolDynamics').hide()
        $('.specialtyDepartment').hide()
        $('.specialist').hide()
        $('.campusOverview').hide()
        $('.schoolEnterpriseCooperation').hide()
        $('.contactUs').show()
    })
    // 底部轮播
    $('.tab_menu li').on('click',function(){
　　　　$(this).addClass("selected").siblings().removeClass("selected");
　　　　var index = $(this).index();
　　　　$(this).parent().siblings().children().eq(index).addClass("active")
　　　　.siblings().removeClass("active")
    })
})
